# Generated by Django 5.2.14 on 2026-06-03 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='receiptdispatch',
            new_name='contributio_status_5b7bfc_idx',
            old_name='contributio_status_84d84e_idx',
        ),
        migrations.RenameIndex(
            model_name='receiptdispatch',
            new_name='contributio_legacy__fb1349_idx',
            old_name='contributio_legacy__b891e0_idx',
        ),
        migrations.RenameIndex(
            model_name='receiptdispatch',
            new_name='contributio_trigger_3c5882_idx',
            old_name='contributio_trigger_47b64a_idx',
        ),
    ]
