# Generated by Django 5.2.14 on 2026-06-06 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_rename_contributio_status_84d84e_idx_contributio_status_5b7bfc_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(db_index=True, unique=True, verbose_name='id legado')),
                ('organization_id', models.IntegerField(db_index=True, verbose_name='organizacao legado')),
                ('person_legacy_id', models.IntegerField(db_index=True, verbose_name='pessoa legada')),
                ('receipt_number', models.CharField(blank=True, max_length=80, verbose_name='numero')),
                ('status', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='status')),
                ('organization_name', models.CharField(blank=True, max_length=240, verbose_name='organizacao')),
                ('person_name', models.CharField(blank=True, max_length=240, verbose_name='nome da pessoa')),
                ('person_code', models.CharField(blank=True, max_length=80, verbose_name='codigo da pessoa')),
                ('person_cpf', models.CharField(blank=True, max_length=32, verbose_name='cpf')),
                ('person_email', models.CharField(blank=True, db_index=True, max_length=254, verbose_name='e-mail')),
                ('person_phone', models.CharField(blank=True, max_length=64, verbose_name='telefone')),
                ('emission_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='data de emissao')),
                ('emission_date_raw', models.CharField(blank=True, max_length=32, verbose_name='data de emissao bruta')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='inicio do periodo')),
                ('period_start_raw', models.CharField(blank=True, max_length=32, verbose_name='inicio do periodo bruto')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='fim do periodo')),
                ('period_end_raw', models.CharField(blank=True, max_length=32, verbose_name='fim do periodo bruto')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor total')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('is_cancelled', models.BooleanField(db_index=True, default=False, verbose_name='cancelado')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='sincronizado em')),
            ],
            options={
                'verbose_name': 'espelho de recibo',
                'verbose_name_plural': 'espelhos de recibos',
                'ordering': ['-emission_date', '-legacy_id'],
                'indexes': [models.Index(fields=['person_legacy_id', 'status', 'emission_date'], name='contributio_person__c1ce04_idx'), models.Index(fields=['person_legacy_id', 'is_cancelled'], name='contributio_person__5a2da8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReceiptItemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(db_index=True, unique=True, verbose_name='id legado')),
                ('contribution_legacy_id', models.IntegerField(db_index=True, verbose_name='contribuicao legada')),
                ('contributor_legacy_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='contribuinte legado')),
                ('received_at', models.DateField(blank=True, db_index=True, null=True, verbose_name='data recebimento')),
                ('received_at_raw', models.CharField(blank=True, max_length=32, verbose_name='data recebimento bruta')),
                ('competence', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='competencia')),
                ('contribution_type_name', models.CharField(blank=True, max_length=160, verbose_name='tipo')),
                ('receipt_method_name', models.CharField(blank=True, max_length=160, verbose_name='forma')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='sincronizado em')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contributions.receiptsnapshot')),
            ],
            options={
                'verbose_name': 'espelho de item de recibo',
                'verbose_name_plural': 'espelhos de itens de recibo',
                'ordering': ['receipt_id', 'received_at', 'legacy_id'],
                'indexes': [models.Index(fields=['receipt', 'competence', 'received_at'], name='contributio_receipt_a88aaf_idx'), models.Index(fields=['contribution_legacy_id'], name='contributio_contrib_f1053c_idx')],
            },
        ),
    ]
