from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contributions", "0005_nativecontribution"),
    ]

    operations = [
        migrations.CreateModel(
            name="NativeEnvelopeLot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("legacy_id", models.IntegerField(db_index=True, unique=True, verbose_name="id publico")),
                ("organization_id", models.IntegerField(db_index=True, verbose_name="organizacao")),
                ("name", models.CharField(max_length=180, verbose_name="nome")),
                ("competence", models.CharField(blank=True, db_index=True, max_length=32, verbose_name="competencia")),
                ("competence_order", models.IntegerField(db_index=True, default=0, verbose_name="ordem da competencia")),
                ("default_received_at", models.DateField(blank=True, null=True, verbose_name="data padrao")),
                ("default_received_at_raw", models.CharField(blank=True, max_length=32, verbose_name="data padrao bruta")),
                ("default_source", models.CharField(blank=True, max_length=160, verbose_name="origem operacional padrao")),
                ("default_contribution_type_legacy_id", models.IntegerField(blank=True, db_index=True, null=True, verbose_name="tipo legado padrao")),
                ("default_campaign_legacy_id", models.IntegerField(blank=True, db_index=True, null=True, verbose_name="campanha legada padrao")),
                ("default_receipt_method_legacy_id", models.IntegerField(blank=True, db_index=True, null=True, verbose_name="forma legada padrao")),
                ("folder_path", models.CharField(blank=True, max_length=500, verbose_name="pasta")),
                ("notes", models.TextField(blank=True, verbose_name="observacoes")),
                ("status", models.CharField(blank=True, db_index=True, max_length=40, verbose_name="status")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="ativo")),
                ("created_by", models.CharField(blank=True, max_length=160, verbose_name="criado por")),
                ("updated_by", models.CharField(blank=True, max_length=160, verbose_name="atualizado por")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
            ],
            options={
                "verbose_name": "lote nativo de envelope",
                "verbose_name_plural": "lotes nativos de envelope",
                "ordering": ["-competence_order", "-legacy_id"],
            },
        ),
        migrations.CreateModel(
            name="NativeEnvelope",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("legacy_id", models.IntegerField(db_index=True, unique=True, verbose_name="id publico")),
                ("organization_id", models.IntegerField(db_index=True, verbose_name="organizacao")),
                ("native_lot_legacy_id", models.IntegerField(blank=True, db_index=True, null=True, verbose_name="lote nativo")),
                ("lot_name", models.CharField(blank=True, max_length=180, verbose_name="nome do lote")),
                ("competence", models.CharField(blank=True, db_index=True, max_length=32, verbose_name="competencia")),
                ("competence_order", models.IntegerField(db_index=True, default=0, verbose_name="ordem da competencia")),
                ("received_at", models.DateField(blank=True, db_index=True, null=True, verbose_name="data de recebimento")),
                ("received_at_raw", models.CharField(blank=True, max_length=32, verbose_name="data de recebimento bruta")),
                ("total_informed", models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="total informado")),
                ("total_lines", models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="total das linhas")),
                ("informed_name", models.CharField(blank=True, max_length=240, verbose_name="nome informado")),
                ("informed_phone", models.CharField(blank=True, max_length=64, verbose_name="telefone informado")),
                ("informed_address", models.CharField(blank=True, max_length=255, verbose_name="endereco informado")),
                ("person_legacy_id", models.IntegerField(blank=True, db_index=True, null=True, verbose_name="pessoa legada")),
                ("contributor_legacy_id", models.IntegerField(blank=True, db_index=True, null=True, verbose_name="contribuinte legado")),
                ("native_aux_contributor_id", models.IntegerField(blank=True, db_index=True, null=True, verbose_name="contribuinte auxiliar nativo")),
                ("receipt_method_legacy_id", models.IntegerField(blank=True, db_index=True, null=True, verbose_name="forma legado")),
                ("receipt_method_name", models.CharField(blank=True, max_length=160, verbose_name="forma")),
                ("operational_status", models.CharField(blank=True, db_index=True, max_length=64, verbose_name="status operacional")),
                ("source", models.CharField(blank=True, max_length=160, verbose_name="origem operacional")),
                ("status", models.CharField(blank=True, db_index=True, max_length=40, verbose_name="status")),
                ("notes", models.TextField(blank=True, verbose_name="observacoes")),
                ("justification", models.TextField(blank=True, verbose_name="justificativa")),
                ("image_original_name", models.CharField(blank=True, max_length=255, verbose_name="nome original da imagem")),
                ("image_hash", models.CharField(blank=True, db_index=True, max_length=120, verbose_name="hash da imagem")),
                ("image_content_type", models.CharField(blank=True, max_length=120, verbose_name="content type da imagem")),
                ("image_size", models.IntegerField(default=0, verbose_name="tamanho da imagem")),
                ("image_path", models.CharField(blank=True, max_length=500, verbose_name="caminho da imagem")),
                ("traceability_form", models.CharField(blank=True, max_length=64, verbose_name="forma identificada")),
                ("traceability_provider", models.CharField(blank=True, max_length=120, verbose_name="banco operadora")),
                ("traceability_check_number", models.CharField(blank=True, max_length=64, verbose_name="numero do cheque")),
                ("traceability_operation_number", models.CharField(blank=True, max_length=64, verbose_name="numero da operacao")),
                ("traceability_nsu_tid", models.CharField(blank=True, max_length=64, verbose_name="nsu tid")),
                ("traceability_card_suffix", models.CharField(blank=True, max_length=32, verbose_name="final do cartao")),
                ("traceability_operation_date", models.DateField(blank=True, null=True, verbose_name="data da operacao")),
                ("traceability_operation_date_raw", models.CharField(blank=True, max_length=32, verbose_name="data da operacao bruta")),
                ("traceability_operation_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="valor da operacao")),
                ("traceability_status", models.CharField(blank=True, max_length=64, verbose_name="status de conciliacao")),
                ("traceability_notes", models.TextField(blank=True, verbose_name="observacoes de conciliacao")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="ativo")),
                ("created_by", models.CharField(blank=True, max_length=160, verbose_name="criado por")),
                ("updated_by", models.CharField(blank=True, max_length=160, verbose_name="atualizado por")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
            ],
            options={
                "verbose_name": "envelope nativo",
                "verbose_name_plural": "envelopes nativos",
                "ordering": ["-competence_order", "-received_at", "-legacy_id"],
            },
        ),
        migrations.CreateModel(
            name="NativeEnvelopeItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("legacy_id", models.IntegerField(db_index=True, unique=True, verbose_name="id publico")),
                ("person_legacy_id", models.IntegerField(blank=True, db_index=True, null=True, verbose_name="pessoa legada")),
                ("contributor_legacy_id", models.IntegerField(blank=True, db_index=True, null=True, verbose_name="contribuinte legado")),
                ("native_aux_contributor_id", models.IntegerField(blank=True, db_index=True, null=True, verbose_name="contribuinte auxiliar nativo")),
                ("contributor_name", models.CharField(blank=True, max_length=240, verbose_name="nome do contribuinte")),
                ("contributor_document", models.CharField(blank=True, max_length=64, verbose_name="documento do contribuinte")),
                ("contribution_legacy_id", models.IntegerField(blank=True, db_index=True, null=True, verbose_name="contribuicao legada")),
                ("contribution_type_legacy_id", models.IntegerField(db_index=True, verbose_name="tipo legado")),
                ("contribution_type_name", models.CharField(blank=True, max_length=160, verbose_name="tipo")),
                ("campaign_legacy_id", models.IntegerField(blank=True, db_index=True, null=True, verbose_name="campanha legada")),
                ("campaign_name", models.CharField(blank=True, max_length=160, verbose_name="campanha")),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="valor")),
                ("notes", models.TextField(blank=True, verbose_name="observacoes")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                ("envelope", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="items", to="contributions.nativeenvelope")),
            ],
            options={
                "verbose_name": "item de envelope nativo",
                "verbose_name_plural": "itens de envelope nativo",
                "ordering": ["envelope_id", "legacy_id"],
            },
        ),
        migrations.AddIndex(
            model_name="nativeenvelopelot",
            index=models.Index(fields=["organization_id", "competence", "status"], name="contributio_organiz_e6ac77_idx"),
        ),
        migrations.AddIndex(
            model_name="nativeenvelope",
            index=models.Index(fields=["organization_id", "competence", "status"], name="contributio_organiz_8d9831_idx"),
        ),
        migrations.AddIndex(
            model_name="nativeenvelope",
            index=models.Index(fields=["organization_id", "person_legacy_id", "is_active"], name="contributio_organiz_77c8d2_idx"),
        ),
        migrations.AddIndex(
            model_name="nativeenvelopeitem",
            index=models.Index(fields=["envelope", "is_active"], name="contributio_envelop_dad314_idx"),
        ),
        migrations.AddIndex(
            model_name="nativeenvelopeitem",
            index=models.Index(fields=["contribution_legacy_id"], name="contributio_contrib_16f11f_idx"),
        ),
    ]
