# Generated by Django 5.2.14 on 2026-06-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0006_nativeenvelope'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contributiontypesnapshot',
            new_name='contributio_organiz_1094a0_idx',
            old_name='contributio_org_idx',
        ),
        migrations.RenameIndex(
            model_name='nativeauxcontributor',
            new_name='contributio_organiz_c55b8a_idx',
            old_name='contributio_organiz_4f7264_idx',
        ),
        migrations.RenameIndex(
            model_name='nativeauxcontributor',
            new_name='contributio_organiz_bfb6b5_idx',
            old_name='contributio_organiz_6960c7_idx',
        ),
        migrations.RenameIndex(
            model_name='nativecontribution',
            new_name='contributio_organiz_c40216_idx',
            old_name='contributio_organiz_9c512a_idx',
        ),
        migrations.RenameIndex(
            model_name='nativecontribution',
            new_name='contributio_organiz_1ce1d2_idx',
            old_name='contributio_organiz_8e48d1_idx',
        ),
        migrations.RenameIndex(
            model_name='nativeenvelope',
            new_name='contributio_organiz_e8fac2_idx',
            old_name='contributio_organiz_8d9831_idx',
        ),
        migrations.RenameIndex(
            model_name='nativeenvelope',
            new_name='contributio_organiz_a9cced_idx',
            old_name='contributio_organiz_77c8d2_idx',
        ),
        migrations.RenameIndex(
            model_name='nativeenvelopeitem',
            new_name='contributio_envelop_2bf9b3_idx',
            old_name='contributio_envelop_dad314_idx',
        ),
        migrations.RenameIndex(
            model_name='nativeenvelopeitem',
            new_name='contributio_contrib_a68409_idx',
            old_name='contributio_contrib_16f11f_idx',
        ),
        migrations.RenameIndex(
            model_name='nativeenvelopelot',
            new_name='contributio_organiz_522fad_idx',
            old_name='contributio_organiz_e6ac77_idx',
        ),
    ]
