# Generated by Django 5.2.14 on 2026-05-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_action_5dc012_idx',
            old_name='audit_audit_action_eb38a1_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_source_6468a5_idx',
            old_name='audit_audit_source_982bd0_idx',
        ),
    ]
