# Generated by Django 5.2.14 on 2026-06-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_centrulesnapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='centrulesnapshot',
            new_name='imports_cen_organiz_e6f0cc_idx',
            old_name='imports_cen_organiz_3d7c94_idx',
        ),
        migrations.RenameIndex(
            model_name='statementimportpilotlot',
            new_name='imports_sta_bank_na_1a60fc_idx',
            old_name='imports_pilot_bank_layout_created_idx',
        ),
        migrations.RenameIndex(
            model_name='statementimportpilotlot',
            new_name='imports_sta_source__7e337c_idx',
            old_name='imports_pilot_source_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='statementimportpilotmovement',
            new_name='imports_sta_lot_id_4a43e4_idx',
            old_name='imports_pilot_lot_review_order_idx',
        ),
        migrations.RenameIndex(
            model_name='statementimportpilotmovement',
            new_name='imports_sta_lot_id_a6161f_idx',
            old_name='imports_pilot_lot_date_amount_idx',
        ),
    ]
